(define (add [x : Int] [y : Int]): Int (+ x y))

(let ([a 1])
(let ([b 2])
(let ([c 3])
(let ([d 4])
(let ([e 5])
(let ([f 6])
(let ([g 7])
(let ([h (add a b)])
    (+ a (+ b (+ c (+ d (+ e (+ f g))))))))))))))
