(define (add [x : (Vector Int)] [y : (Vector Int)]): (Vector Int)
    (vector (+ (vector-ref x 0) (vector-ref y 0))))

(let ((a (vector 1)))
(let ((b (vector 2)))
(let ((c (vector 3)))
(let ((d (vector 4)))
(let ((e (vector 5)))
(let ((f (vector 6)))
(let ((g (vector 7)))
(let ((h (add a b)))
    (+ (vector-ref a 0) (+ (vector-ref b 0) (+ (vector-ref c 0) (+ (vector-ref d 0) (+ (vector-ref e 0) (+ (vector-ref f 0) (vector-ref g 0)))))))))))))))
